2025-04-24 00:21:29 --- Archivo 2025-04-24 00.21.log creado con éxito en H:\Python\Administradores de Bases de Datos P. Final\static\logs\2025-04-24 00.21.log
2025-04-24 00:21:29 ---  * Debugger is active!
2025-04-24 00:21:29 ---  * Debugger PIN: 827-411-152
2025-04-24 00:21:46 --- 127.0.0.1 - - [24/Apr/2025 00:21:46] "[35m[1mGET /cookies HTTP/1.1[0m" 500 -
2025-04-24 00:21:49 --- 127.0.0.1 - - [24/Apr/2025 00:21:49] "[35m[1mGET /cookies HTTP/1.1[0m" 500 -
2025-04-24 00:21:50 --- Error on request:
Traceback (most recent call last):
  File "C:\Users\angel\AppData\Roaming\Python\Python311\site-packages\werkzeug\debug\__init__.py", line 330, in debug_application
    app_iter = self.app(environ, start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\angel\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\angel\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\angel\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\angel\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\angel\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\angel\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Python\Administradores de Bases de Datos P. Final\routhes\misc.py", line 28, in load_cookies
  File "H:\Python\Administradores de Bases de Datos P. Final\routhes\misc.py", line 19, in get_signing_serializer
    email = request.form["email"]
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\angel\AppData\Roaming\Python\Python311\site-packages\flask\sessions.py", line 296, in get_signing_serializer
    if not app.secret_key:
           ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'secret_key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\angel\AppData\Roaming\Python\Python311\site-packages\werkzeug\serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "C:\Users\angel\AppData\Roaming\Python\Python311\site-packages\werkzeug\serving.py", line 325, in execute
    for data in application_iter:
  File "C:\Users\angel\AppData\Roaming\Python\Python311\site-packages\werkzeug\debug\__init__.py", line 345, in debug_application
    html = tb.render_debugger_html(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\angel\AppData\Roaming\Python\Python311\site-packages\werkzeug\debug\tbtools.py", line 333, in render_debugger_html
    "summary": self.render_traceback_html(include_title=False),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\angel\AppData\Roaming\Python\Python311\site-packages\werkzeug\debug\tbtools.py", line 293, in render_traceback_html
    row_parts.append(f"<li{info}>{frame.render_html(mark_library)}")
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\angel\AppData\Roaming\Python\Python311\site-packages\werkzeug\debug\tbtools.py", line 415, in render_html
    render_line(lines[line_idx], "current")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
2025-04-24 00:21:50 --- Error on request:
Traceback (most recent call last):
  File "C:\Users\angel\AppData\Roaming\Python\Python311\site-packages\werkzeug\debug\__init__.py", line 330, in debug_application
    app_iter = self.app(environ, start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\angel\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\angel\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\angel\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\angel\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\angel\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\angel\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Python\Administradores de Bases de Datos P. Final\routhes\misc.py", line 28, in load_cookies
  File "H:\Python\Administradores de Bases de Datos P. Final\routhes\misc.py", line 19, in get_signing_serializer
    email = request.form["email"]
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\angel\AppData\Roaming\Python\Python311\site-packages\flask\sessions.py", line 296, in get_signing_serializer
    if not app.secret_key:
           ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'secret_key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\angel\AppData\Roaming\Python\Python311\site-packages\werkzeug\serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "C:\Users\angel\AppData\Roaming\Python\Python311\site-packages\werkzeug\serving.py", line 325, in execute
    for data in application_iter:
  File "C:\Users\angel\AppData\Roaming\Python\Python311\site-packages\werkzeug\debug\__init__.py", line 345, in debug_application
    html = tb.render_debugger_html(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\angel\AppData\Roaming\Python\Python311\site-packages\werkzeug\debug\tbtools.py", line 333, in render_debugger_html
    "summary": self.render_traceback_html(include_title=False),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\angel\AppData\Roaming\Python\Python311\site-packages\werkzeug\debug\tbtools.py", line 293, in render_traceback_html
    row_parts.append(f"<li{info}>{frame.render_html(mark_library)}")
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\angel\AppData\Roaming\Python\Python311\site-packages\werkzeug\debug\tbtools.py", line 415, in render_html
    render_line(lines[line_idx], "current")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
2025-04-24 00:21:57 --- 127.0.0.1 - - [24/Apr/2025 00:21:57] "GET /myprofile HTTP/1.1" 200 -
2025-04-24 00:21:58 --- 127.0.0.1 - - [24/Apr/2025 00:21:58] "[33mGET /static/images/users/default.png HTTP/1.1[0m" 404 -
2025-04-24 00:21:58 --- 127.0.0.1 - - [24/Apr/2025 00:21:58] "[36mGET /static/styles/bootstrap.css HTTP/1.1[0m" 304 -
2025-04-24 00:21:58 --- 127.0.0.1 - - [24/Apr/2025 00:21:58] "[36mGET /static/js/bootstrap.js HTTP/1.1[0m" 304 -
2025-04-24 00:21:58 --- 127.0.0.1 - - [24/Apr/2025 00:21:58] "[36mGET /static/styles/chow.css HTTP/1.1[0m" 304 -
2025-04-24 00:21:58 --- 127.0.0.1 - - [24/Apr/2025 00:21:58] "[36mGET /static/js/popper.js HTTP/1.1[0m" 304 -
2025-04-24 00:22:31 --- 127.0.0.1 - - [24/Apr/2025 00:22:31] "[32mGET /logout HTTP/1.1[0m" 302 -
2025-04-24 00:22:31 --- 127.0.0.1 - - [24/Apr/2025 00:22:31] "GET / HTTP/1.1" 200 -
2025-04-24 00:22:31 --- 127.0.0.1 - - [24/Apr/2025 00:22:31] "[36mGET /static/styles/bootstrap.css HTTP/1.1[0m" 304 -
2025-04-24 00:22:31 --- 127.0.0.1 - - [24/Apr/2025 00:22:31] "[36mGET /static/styles/chow_cards.css HTTP/1.1[0m" 304 -
2025-04-24 00:22:31 --- 127.0.0.1 - - [24/Apr/2025 00:22:31] "[36mGET /static/styles/chow.css HTTP/1.1[0m" 304 -
2025-04-24 00:22:31 --- 127.0.0.1 - - [24/Apr/2025 00:22:31] "[36mGET /static/js/popper.js HTTP/1.1[0m" 304 -
2025-04-24 00:22:31 --- 127.0.0.1 - - [24/Apr/2025 00:22:31] "[36mGET /static/images/web/leche.jpg HTTP/1.1[0m" 304 -
2025-04-24 00:22:32 --- 127.0.0.1 - - [24/Apr/2025 00:22:32] "[36mGET /static/images/web/ventas.jpg HTTP/1.1[0m" 304 -
2025-04-24 00:22:32 --- 127.0.0.1 - - [24/Apr/2025 00:22:32] "[36mGET /static/images/web/contactanos.jpg HTTP/1.1[0m" 304 -
2025-04-24 00:22:32 --- 127.0.0.1 - - [24/Apr/2025 00:22:32] "[36mGET /static/js/bootstrap.js HTTP/1.1[0m" 304 -
